Algoritmo "OrientacaoAObjeto"

tipo
cadastroCliente = registro
	nome: caractere
	rg: caractere
	idade: inteiro
fimregistro

Var
cliente1 : cadastroCliente



Inicio
Escreval ("Digite o seu nome: ")
leia(cliente1.nome)

Escreval ("Digite o seu rg: ")
leia(cliente1.rg)

Escreval ("Digite a sua idade: ")
leia(cliente1.idade)

Escreval ("Nome: ", cliente1.nome)
Escreval ("RG: ", cliente1.rg)
Escreval ("idade: ", cliente1.idade)


Fimalgoritmo