Algoritmo "Trabalhando com tipos"

Var

   palavra1, palavra2, palavra3: caracter
   numero1, numero2, numero3: inteiro
Inicio
    Escreval("palavra 1:")
    leia(palavra1)
    Escreval("palavra 2:")
    leia(palavra2)
    Escreval("numero 1:")
    leia(numero1)
    Escreval("numero 2:")
    leia(numero2)
    palavra3 <- palavra1 + " " + palavra2
    numero3 <- numero1+ numero2
    Escreval(palavra3)
    Escreval(numero3)

Fimalgoritmo